### ISSUE TITLE
SV filtration fails for old cases.

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1741]
**Describe the bug**
SV filtration does not work for old cases.

**Expected behavior**
Filtration should work.

**Additional context**
```
[2024-06-26 03:40:42,008: WARNING/ForkPoolWorker-16] Traceback (most recent call last):
  File "/usr/src/app/svs/models/jobs.py", line 477, in run_sv_query_bg_job
    _inner(tmpdir)
  File "/usr/src/app/svs/models/jobs.py", line 352, in _inner
    _write_header(outputf, filter_job.case, list(sorted(callers)))
  File "/usr/src/app/svs/models/jobs.py", line 218, in _write_header
    name, version = caller.split("v")
ValueError: too many values to unpack (expected 2)
```

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
Old data contains caller strings ` ERDSv1.1+SV2v1.4.3.4`. This does not work with the new `jobs.py`.
