### ISSUE TITLE
Fix Selenium-related problem with tests

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#490]
**Describe the bug**
A test fails sporadically.

**To Reproduce**
Stochastic failure in CI.

CI Link: https://github.com/bihealth/varfish-server/runs/6319511656?check_suite_focus=true

```
Traceback (most recent call last):
  File "/home/runner/work/varfish-server/varfish-server/variants/tests/test_ui.py", line 678, in test_variant_filter_case_multi_bookmark_one_variant
    self.assertTrue(selectors[0].is_selected())
AssertionError: False is not true
```

**Expected behavior**
Tests should run through.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Here is another one:

- https://github.com/bihealth/varfish-server/actions/runs/4435755612/jobs/7783318429#step:10:2019

```
======================================================================
FAIL: test_variant_filter_case_multi_bookmark_one_variant (variants.tests.test_ui.TestVariantsCaseFilterViewExtraAnno)
Test if submitting the filter yields the expected results.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/varfish-server/varfish-server/variants/tests/test_ui.py", line 676, in test_variant_filter_case_multi_bookmark_one_variant
    self.assertTrue(selectors[0].is_selected())
AssertionError: False is not true
```

**Comment by holtgrewe** [comment]
Not relevant any more with Vue.js UI, can be recreated if it reappears.
